spring:
  application:
    name: kafka-spring-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: example
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1
      fetch-max-wait: 36000
      enable-auto-commit: true
      client-id: example
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: record